---
language: php
install: composer install
script: 'echo "Ok!"'
after_success: build/build.sh
deploy:
  provider: releases
  api_key:
      secure: "S1/SXlaCjNwBRZLZ5OCeH6z8gF7uWUul1QWKkLnLEjcfMyWRGeJSycAhyWphR3BVKJ08wZzgPD2NC2Gm65qt/UWDhgbi0XImHD3latFO4k18VNmX+yxB28z2n2RY8LU5LHZhOeqcmqED7L6CSS3xWrARP6cxeh29DTlBSEoJFiyS3M6NpzOW8wcOKV9eWoi3v4wkTUK/2xXXChx+iBESQYEeSCcXQ+3Gat2y9QHQRAgwJ9Fng4e/2p6aHeEN1rnkNaNRZcb+cPrddELJxEC5p+dOmD6XjILXHO5/C6C9rhIgeXj9kpq49VDANIkB2UI0eD6cOvVD2kadOWIiUazcnZrxklW7PoJISwGgBVBHIpneIiisk5kh1CUaCcx6FPhoPZByu31Z0Gf1x6zHjlbFfLN5bSx2F4z/0jRmD8A4mhBdXkuTVxUV9tuLyA74RqM3urv4YJi8jXHYMvR+K0chux/0sW/UQUv9C6cyCWtxqVsbgSC/Q8VBFLuqzmRbGjtWGrI1JwCbjQz0tu3S7rv+dI3lzvvpErth5qvi4lcDVHAWRYrj9PA9rJIAm5RoH09kPFz/KUFY10uKjSDvNsVazx+qsQHP9W9c6oq+ic+lRtffF3JWIuUPFvMm4Vvvw1Iz5qfwAdNV2eVS6D4lo4j1b6Rsm3q2bBXmXy2Qpm48pM8="
  file: build/HitmeMarketplace.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true