---
language: php
install: composer install
script: 'echo "Ok!"'
after_success: build/build.sh
deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: build/HitmeMarketplace.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true