---
language: php
install: composer install
script: 'echo "Ok!"'
after_success: build/build.sh
deploy:
  provider: releases
  api_key:
    secure: "ZwYAdf7xqLVyffEdoPFK6l9zgioJx4YYE2YxPT1uTb4AuQT6liG3ItLCBpwIFco7g0mrI9IRr9aSBTH6XTbSKdqSkIM1T8HtTo409lervtIanw5Na307lBN6vFnokrAUWYwqccBiGsJG+QdAMTZVHQDBEJMC55/ytyHOar2OCRpJb3DfQkPouO2qN5x10sAFjIOaQ40haQYUmDleTmZLCV271E2JGVLLyX+a6bedidHHId3XX33sxbbf70+BZUiTlACfs0SxTAOXABYi2jsT8KJsu99W815OLDqspZ7SYnbux3PrBE1K0uronLj3mh/fEqHpQw4mm4iu+0m02p9hPv0OVc9jlMTS01ZjtIjX1SX3COwLk4Gxggy/7jeCyjTAkMXKJSnwN2ks1/iACJmTWdVcRxs2qV+j4hKOiYGiVm1NOdkC39CUV4SJ8CY0TGOPhfrtXU+8385MnB5pTO1/8T2Yk1kPzkQK1Jtd6aZWcMH2SHUNpSf34rZxBq6IyXo66Mu+hC2vfPtKT2TC7Q+b1Kn7DkfPs22DxOId5H1Fpdc6W4Ta+0bLE90c9im4TK8UQRtbCozlE74wD7eS+8qwPpL3rir4D/YCpP8lawB/zeh342IIQzFIATjCdx+r3HsEie2ssn4wO0sc+w5LlKXrpMZdW9pCWXeCHbtYVBecLu0="
  file: build/HitmeMarketplace.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true